version: '3.8'

services:
  # db:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  #     PGDATA: /var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4:5.5
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: secret
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

  backend:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      KEY_FIREBASE: ${KEY_FIREBASE}

    volumes:
      - ./Backend/:/app/
volumes:
  db-data:
  pgadmin-data: